---
- name: remove all things related to cluster
  shell: kubeadm reset -f
  ignore_errors: yes   

- name: init cluster
  command: kubeadm init --pod-network-cidr="10.244.0.0/16" \
        --apiserver-advertise-address="{{ansible_host}}" \
        --control-plane-endpoint="{{ansible_host}}" \ --ignore-preflight-errors=NumCPU,Mem
  register: kubeadd_cmd
  args:
    chdir: /home/ec2-user

- name: Mostrando la salida de la ejecución del kubeadm init
  debug:
    msg: "{{ kubeadd_cmd.stdout_lines }}"

- pause: seconds=30

- name: Create dir for .kube
  file:
    path: /home/ec2-user/.kube
    state: directory

- name: copy configuration file to the newly created dir
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ec2-user/.kube/config
    remote_src: yes

- name: set kubeconfig file permissions
  file:
    path: /home/ec2-user/.kube/config
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: Set flannel for networking between pods
  become: yes
  become_user: ec2-user
  shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

- name: Get join token
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Copy join command to local file.    
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777