---
- name: empty file for Kubeadm configure
  copy:
    content: ""
    dest: /etc/kubernetes/kubeadm-config.yaml
    force: no

- name: configure container runtime with cgroup driver
  blockinfile:
    path: /etc/kubernetes/kubeadm-config.yaml
    block: |
        kind: ClusterConfiguration
        apiVersion: kubeadm.k8s.io/v1beta3
        networking:
          podSubnet: "10.244.0.0/16"
        ---
        kind: KubeletConfiguration
        apiVersion: kubelet.config.k8s.io/v1beta1
        runtimeRequestTimeout: "15m"
        cgroupDriver: "systemd"
        systemReserved:
          cpu: 100m
          memory: 350M
        kubeReserved:
          cpu: 100m
          memory: 50M
        enforceNodeAllocatable:
        - pods


- name: init cluster
  command: kubeadm init 
  run_once: true
  args:
    chdir: /home/ec2-user

- name: Create dir for .kube
  file:
    path: /home/ec2-user/.kube
    state: directory

- name: copy configuration file to the newly created dir
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ec2-user/.kube/config
    remote_src: yes

- name: set kubeconfig file permissions
  file:
    path: /home/ec2-user/.kube/config
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: Set calico for networking between pods
  become: yes
  become_user: ec2-user
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

- name: Get join token
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Copy join command to local file.    
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777