plugin: amazon.aws.aws_ec2

# This sets the region. If empty (the default) default this will include all regions, except possibly
# restricted ones like us-gov-west-1 and cn-north-1.
regions:
- us-east-1

keyed_groups:
  - key: tags.Role
    separator: ''


include_filters:
- tag:Environment:
  - 'qa'

hostnames:
  - tag:Name

compose:
  ansible_host: private_ip_address
  ansible_user: ec2-user
  ansible_python_interpreter: /usr/bin/python3
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no'