---

- name: Download GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Set Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Update apt
  apt:
    update_cache: yes

- name: Install containerd
  apt:
    name: containerd.io
    state: present

- name: Create dir container d
  file:
    path: /etc/containerd
    state: directory

- name: configure container d
  shell: containerd config default | tee /etc/containerd/config.toml > /dev/null

- name: change systemdgroup 
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup = false$'
    line: SystemdCgroup = true

- name: restart containerd service
  service:
    name: containerd
    state: restarted
    enabled: yes
