---

- name: Ensure the repo docker
  shell: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Update apt
  dnf:
    update_cache: yes

- name: Install containerd
  dnf:
    name: containerd.io
    state: present

- name: Create dir container d
  file:
    path: /etc/containerd
    state: directory

- name: configure container d
  shell: containerd config default | tee /etc/containerd/config.toml > /dev/null

- name: change systemdgroup 
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup = false$'
    line: SystemdCgroup = true

- name: restart containerd service
  service:
    name: containerd
    state: restarted
    enabled: yes
