---

- name: Create an empty file for the containerd module
  copy:
    content: ""
    dest: /etc/modules-load.d/containerd.conf
    force: no

- name: Configure modules for containerd
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: Update yum
  yum:
    update_cache: yes

- name: Install containerd
  yum:
    name: containerd
    state: present

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Add containerd configuration
  shell: /usr/bin/containerd config default > /etc/containerd/config.toml

- name: change systemdgroup 
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup = false$'
    line: SystemdCgroup = true

- name: Enable the containerd service and start service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes