---

- name: Configuring Yum repo for Kubernetes
  yum_repository:
    name: Kubernetes
    description: Yum for Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes

- name: Update apt
  yum:
    update_cache: yes

- name: Install Kubelet
  yum:
    name: kubelet
    state: present

- name: Install Kubectl
  yum:
    name: kubectl
    state: present

- name: Install kubeadm
  yum:
    name: kubeadm
    state: present

- name: Load modules for IP Forwarding
  shell: | 
          modprobe overlay
          modprobe br_netfilter

- name: Config for iptables
  blockinfile:
    path: /etc/sysctl.d/kubernetes.conf
    create: yes
    block: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
            net.ipv4.ip_forward = 1

- name: make all IPconfig persistent
  shell: echo br_netfilter | tee /etc/modules-load.d/kubernetes.conf

- name: configure sysctl
  shell: sysctl --system

