---
- name: Create an empty file for K8S sysctl parameters
  copy:
    content: ""
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    force: no

- name: Configure sysctl parameters for K8S
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "{{ item }}"
  with_items:
    - "net.bridge.bridge-nf-call-iptables  = 1"
    - "net.ipv4.ip_forward                 = 1"
    - "net.bridge.bridge-nf-call-ip6tables = 1"

- name: Apply sysctl parameters
  command: sysctl --system

- name: Configuring Kubernetes Repo
  yum_repository:
    name: kubernetes
    description: Repositorio oficial de Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
    exclude: kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: Update apt
  yum:
    update_cache: yes

- name: Installing required packages
  yum:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  with_items:
    - kubelet
    - kubeadm

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Set bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: Set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Reboot instance.
  reboot:
    post_reboot_delay: 20
    reboot_timeout: 80
    connect_timeout: 80
    test_command: uptime

- name: "Waiting for the server to come back up"
  local_action: 
    wait_for host={{ internal_ip }} 
    port=22 state=started delay=30 timeout=300
  become: false

- name: enable Kubernetes service
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no