---
- name: Update apt
  yum:
    update_cache: yes

- name: Install yum utils
  yum:
    name: yum-utils
    state: present

- name: Install tc
  yum:
    name: iproute-tc
    state: present

- name: Disable SWAP
  shell: |
    swapoff -a

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'



